server.address=0.0.0.0
server.port=8080
spring.datasource.url=jdbc:postgresql://ep-withered-block-ao91741e-pooler.c-2.ap-southeast-1.aws.neon.tech/Ledger_app?user=neondb_owner&password=npg_SjnXpIU9tH2C&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SjnXpIU9tH2C

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect